
/* Drop Tables */

DROP TABLE ANSWER CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE ADMINS CASCADE CONSTRAINTS;
DROP TABLE GIFTICON_EXCHANGE CASCADE CONSTRAINTS;
DROP TABLE GIFTICON CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE MENU CASCADE CONSTRAINTS;
DROP TABLE BRAND CASCADE CONSTRAINTS;
DROP TABLE QUESTION CASCADE CONSTRAINTS;
DROP TABLE MEMBERS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ADMINS
(
	ADMIN_CODE char(1) NOT NULL,
	ADMIN_ID varchar2(20) NOT NULL UNIQUE,
	ADMIN_PW varchar2(20) NOT NULL,
	ADMIN_NAME varchar2(51) NOT NULL,
	PRIMARY KEY (ADMIN_CODE)
);


CREATE TABLE ANSWER
(
	MEMBER_CODE varchar2(5) NOT NULL,
	QSTN_CODE varchar2(3) NOT NULL,
	ANSWER_CODE char(1) NOT NULL,
	ADMIN_CODE char(1) NOT NULL,
	ANSWER_CONTENT varchar2(1000) NOT NULL,
	ANSWER_DATE date NOT NULL,
	PRIMARY KEY (MEMBER_CODE, QSTN_CODE, ANSWER_CODE)
);


CREATE TABLE BRAND
(
	BRAND_CODE varchar2(2) NOT NULL,
	BRAND_NAME varchar2(30) NOT NULL UNIQUE,
	BRAND_IMG varchar2(150) NOT NULL,
	BRAND_DESCRIPTION varchar2(1500),
	BRAND_LINK varchar2(150) NOT NULL UNIQUE,
	PRIMARY KEY (BRAND_CODE)
);


CREATE TABLE GIFTICON
(
	GIFTICON_CODE varchar2(3) NOT NULL,
	BRAND_CODE varchar2(2) NOT NULL,
	MENU_CODE varchar2(2) NOT NULL,
	GIFTICON_NAME varchar2(50) NOT NULL,
	GIFTICON_IMG varchar2(150) NOT NULL,
	GIFTICON_PRICE number(5) NOT NULL,
	GIFTICON_DATE date NOT NULL,
	PRIMARY KEY (GIFTICON_CODE)
);


CREATE TABLE GIFTICON_EXCHANGE
(
	GIFTICON_EXCODE varchar2(5) NOT NULL,
	MEMBER_CODE varchar2(5) NOT NULL,
	GIFTICON_CODE varchar2(3) NOT NULL,
	GIFTICON_NUMBER varchar2(10) NOT NULL,
	GIFTICON_EXDATE date NOT NULL,
	PRIMARY KEY (GIFTICON_EXCODE)
);


CREATE TABLE MEMBERS
(
	MEMBER_CODE varchar2(5) NOT NULL,
	MEMBER_ID varchar2(20) NOT NULL UNIQUE,
	MEMBER_PW varchar2(20) NOT NULL,
	MEMBER_NAME varchar2(51) NOT NULL,
	MEMBER_NICKNAME varchar2(30) NOT NULL UNIQUE,
	MEMBER_EMAIL varchar2(50) NOT NULL UNIQUE,
	MEMBER_NUMBER varchar2(11) NOT NULL UNIQUE,
	MEMBER_DATE date NOT NULL,
	HOLD_POINT number(6) NOT NULL,
	PRIMARY KEY (MEMBER_CODE)
);


CREATE TABLE MENU
(
	BRAND_CODE varchar2(2) NOT NULL,
	MENU_CODE varchar2(2) NOT NULL,
	MENU_NAME varchar2(45) NOT NULL,
	MENU_IMG varchar2(150) NOT NULL,
	MENU_PRICE number(5) NOT NULL,
	MENU_DESCRIPTION varchar2(1500),
	MENU_INGREDIENTS varchar2(21) NOT NULL,
	PRIMARY KEY (BRAND_CODE, MENU_CODE)
);


CREATE TABLE NOTICE
(
	ADMIN_CODE char(1) NOT NULL,
	NOTICE_CODE varchar2(3) NOT NULL,
	NOTICE_TITLE varchar2(500) NOT NULL,
	NOTICE_CONTENT varchar2(1500) NOT NULL,
	NOTICE_DATE date NOT NULL,
	NOTICE_IMG varchar2(150),
	PRIMARY KEY (ADMIN_CODE, NOTICE_CODE)
);


CREATE TABLE QUESTION
(
	MEMBER_CODE varchar2(5) NOT NULL,
	QSTN_CODE varchar2(3) NOT NULL,
	QSTN_TITLE varchar2(300) NOT NULL,
	QSTN_CONTENT varchar2(1000) NOT NULL,
	QSTN_DATE date NOT NULL,
	QSTN_CONFIRM varchar2(9) NOT NULL,
	QSTN_IMG varchar2(150),
	PRIMARY KEY (MEMBER_CODE, QSTN_CODE)
);


CREATE TABLE REVIEW
(
	BRAND_CODE varchar2(2) NOT NULL,
	MENU_CODE varchar2(2) NOT NULL,
	REVIEW_CODE varchar2(4) NOT NULL,
	MEMBER_CODE varchar2(5) NOT NULL,
	REVIEW_SCORE number(2,1) NOT NULL,
	REVIEW_CONTENT varchar2(1500),
	REVIEW_DATE date NOT NULL,
	REVIEW_IMG varchar2(150),
	REVIEW_CONFIRM char(1) NOT NULL,
	EARN_POINT number(4) NOT NULL,
	EARNDATE_POINT date NOT NULL,
	PRIMARY KEY (BRAND_CODE, MENU_CODE, REVIEW_CODE)
);



/* Create Foreign Keys */

ALTER TABLE ANSWER
	ADD FOREIGN KEY (ADMIN_CODE)
	REFERENCES ADMINS (ADMIN_CODE)
	ON DELETE CASCADE
;


ALTER TABLE NOTICE
	ADD FOREIGN KEY (ADMIN_CODE)
	REFERENCES ADMINS (ADMIN_CODE)
	ON DELETE CASCADE
;


ALTER TABLE MENU
	ADD FOREIGN KEY (BRAND_CODE)
	REFERENCES BRAND (BRAND_CODE)
	ON DELETE CASCADE
;


ALTER TABLE GIFTICON_EXCHANGE
	ADD FOREIGN KEY (GIFTICON_CODE)
	REFERENCES GIFTICON (GIFTICON_CODE)
	ON DELETE CASCADE
;


ALTER TABLE GIFTICON_EXCHANGE
	ADD FOREIGN KEY (MEMBER_CODE)
	REFERENCES MEMBERS (MEMBER_CODE)
	ON DELETE CASCADE
;


ALTER TABLE QUESTION
	ADD FOREIGN KEY (MEMBER_CODE)
	REFERENCES MEMBERS (MEMBER_CODE)
	ON DELETE CASCADE
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (MEMBER_CODE)
	REFERENCES MEMBERS (MEMBER_CODE)
	ON DELETE CASCADE
;


ALTER TABLE GIFTICON
	ADD FOREIGN KEY (BRAND_CODE, MENU_CODE)
	REFERENCES MENU (BRAND_CODE, MENU_CODE)
	ON DELETE CASCADE
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (BRAND_CODE, MENU_CODE)
	REFERENCES MENU (BRAND_CODE, MENU_CODE)
	ON DELETE CASCADE
;


ALTER TABLE ANSWER
	ADD FOREIGN KEY (MEMBER_CODE, QSTN_CODE)
	REFERENCES QUESTION (MEMBER_CODE, QSTN_CODE)
	ON DELETE CASCADE
;



